<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="perfectMatch" tests="84" failures="21" timestamp="2021-08-05T13:43:39 IST" time="142.936" errors="0">
  <testcase name="C11_BankFee" time="20.37" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="1.309" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="1.224" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="1.223" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_BankFee(Dev_InboundTesting.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_Deduction" time="1.271" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="1.215" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="1.204" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="1.255" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_Deduction(Dev_InboundTesting.java:319)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Discount" time="1.594" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="1.196" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="1.24" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="1.275" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_Discount(Dev_InboundTesting.java:336)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_DuplicatePayment" time="1.829" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_DuplicatePayment -->
  <testcase name="C11_DuplicatePayment" time="1.248" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_DuplicatePayment -->
  <testcase name="C11_DuplicatePayment" time="4.056" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_DuplicatePayment -->
  <testcase name="C11_DuplicatePayment" time="1.853" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_DuplicatePayment(Dev_InboundTesting.java:387)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_DuplicatePayment -->
  <testcase name="C11_OnAccount" time="1.402" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OnAccount -->
  <testcase name="C11_OnAccount" time="1.167" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OnAccount -->
  <testcase name="C11_OnAccount" time="1.889" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OnAccount -->
  <testcase name="C11_OnAccount" time="1.168" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_OnAccount(Dev_InboundTesting.java:248)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_OnAccount -->
  <testcase name="C11_OverPayment" time="1.781" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OverPayment -->
  <testcase name="C11_OverPayment" time="1.16" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OverPayment -->
  <testcase name="C11_OverPayment" time="1.186" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_OverPayment -->
  <testcase name="C11_OverPayment" time="1.169" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_OverPayment(Dev_InboundTesting.java:284)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_OverPayment -->
  <testcase name="C11_PartailPayment" time="1.387" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PartailPayment -->
  <testcase name="C11_PartailPayment" time="1.158" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PartailPayment -->
  <testcase name="C11_PartailPayment" time="1.203" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PartailPayment -->
  <testcase name="C11_PartailPayment" time="1.166" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_PartailPayment(Dev_InboundTesting.java:353)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_PartailPayment -->
  <testcase name="C11_PerfectMatch" time="1.582" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PerfectMatch -->
  <testcase name="C11_PerfectMatch" time="1.131" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PerfectMatch -->
  <testcase name="C11_PerfectMatch" time="1.176" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_PerfectMatch -->
  <testcase name="C11_PerfectMatch" time="1.167" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_PerfectMatch(Dev_InboundTesting.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_PerfectMatch -->
  <testcase name="C11_ShortPayment" time="1.481" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_ShortPayment -->
  <testcase name="C11_ShortPayment" time="1.137" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_ShortPayment -->
  <testcase name="C11_ShortPayment" time="1.14" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_ShortPayment -->
  <testcase name="C11_ShortPayment" time="1.188" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_ShortPayment(Dev_InboundTesting.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_ShortPayment -->
  <testcase name="C11_Writeoff" time="1.484" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="1.17" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="1.185" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="1.207" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.C11_Writeoff(Dev_InboundTesting.java:370)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="P10_BankFee" time="1.787" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_BankFee -->
  <testcase name="P10_BankFee" time="1.185" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_BankFee -->
  <testcase name="P10_BankFee" time="1.151" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_BankFee -->
  <testcase name="P10_BankFee" time="1.158" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_BankFee(Dev_InboundTesting.java:89)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_BankFee -->
  <testcase name="P10_Deduction" time="1.537" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Deduction -->
  <testcase name="P10_Deduction" time="1.157" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Deduction -->
  <testcase name="P10_Deduction" time="1.122" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Deduction -->
  <testcase name="P10_Deduction" time="1.122" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_Deduction(Dev_InboundTesting.java:107)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_Deduction -->
  <testcase name="P10_DelCred" time="4.06" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DelCred -->
  <testcase name="P10_DelCred" time="1.521" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DelCred -->
  <testcase name="P10_DelCred" time="1.157" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DelCred -->
  <testcase name="P10_DelCred" time="1.179" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_DelCred(Dev_InboundTesting.java:160)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_DelCred -->
  <testcase name="P10_Discount" time="1.719" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Discount -->
  <testcase name="P10_Discount" time="1.158" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Discount -->
  <testcase name="P10_Discount" time="1.192" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_Discount -->
  <testcase name="P10_Discount" time="2.868" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_Discount(Dev_InboundTesting.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_Discount -->
  <testcase name="P10_DuplicatePayment" time="1.439" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DuplicatePayment -->
  <testcase name="P10_DuplicatePayment" time="1.596" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DuplicatePayment -->
  <testcase name="P10_DuplicatePayment" time="1.13" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_DuplicatePayment -->
  <testcase name="P10_DuplicatePayment" time="1.133" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_DuplicatePayment(Dev_InboundTesting.java:141)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_DuplicatePayment -->
  <testcase name="P10_OnAccount" time="2.682" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="1.165" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="1.242" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="1.175" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_OnAccount(Dev_InboundTesting.java:194)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OverPayment" time="1.564" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="1.147" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="1.205" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="1.451" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_OverPayment(Dev_InboundTesting.java:124)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_PartialPayment" time="4.426" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PartialPayment -->
  <testcase name="P10_PartialPayment" time="1.137" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PartialPayment -->
  <testcase name="P10_PartialPayment" time="1.149" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PartialPayment -->
  <testcase name="P10_PartialPayment" time="4.617" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_PartialPayment(Dev_InboundTesting.java:211)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_PartialPayment -->
  <testcase name="P10_PerfectMatch" time="4.118" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="1.605" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="1.15" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="1.688" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_PerfectMatch(Dev_InboundTesting.java:55)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_ShortPayment" time="0.927" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.001" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.002" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.004" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.IllegalArgumentException" message="body cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: body cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:679)
at com.simple.restassured.RestCalls.PostRequest(RestCalls.java:44)
at Inbound_Testing.Dev_InboundTesting.P10_ShortPayment(Dev_InboundTesting.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_WriteOff" time="1.553" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_WriteOff -->
  <testcase name="P10_WriteOff" time="1.14" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_WriteOff -->
  <testcase name="P10_WriteOff" time="1.153" classname="Inbound_Testing.Dev_InboundTesting">
    <skipped/>
  </testcase> <!-- P10_WriteOff -->
  <testcase name="P10_WriteOff" time="1.152" classname="Inbound_Testing.Dev_InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.Dev_InboundTesting.P10_WriteOff(Dev_InboundTesting.java:177)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_WriteOff -->
</testsuite> <!-- perfectMatch -->
