<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="27" hostname="Lenovo-PC" name="Inbound_Testing.InboundTesting" tests="45" failures="8" timestamp="2021-04-29T14:09:31 IST" time="145.153" errors="1">
  <testcase name="P10_OverPayment" time="2.812" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_OverPayment(InboundTesting.java:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- P10_OverPayment -->
  <system-out/>
  <testcase name="C11_BankFee" time="8.408" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <system-out/>
  <testcase name="C11_Discount" time="2.986" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <system-out/>
  <testcase name="P10_OverPayment" time="4.108" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <system-out/>
  <testcase name="C11_Sundry" time="4.082" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Sundry(InboundTesting.java:330)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- C11_Sundry -->
  <system-out/>
  <testcase name="P10_OnAccount" time="2.246" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <system-out/>
  <testcase name="C11_Sundry" time="2.811" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <system-out/>
  <testcase name="C11_BankFee" time="3.144" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_BankFee(InboundTesting.java:276)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- C11_BankFee -->
  <system-out/>
  <testcase name="C11_Deduction" time="2.369" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Deduction(InboundTesting.java:294)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- C11_Deduction -->
  <system-out/>
  <testcase name="P10_ShortPayment" time="0.005" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <system-out/>
  <testcase name="P10_WriteOff" time="2.518" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="P10_ShortPayment" time="0.006" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <system-out/>
  <testcase name="P10_OnAccount" time="2.834" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <system-out/>
  <testcase name="P10_ShortPayment" time="1.141" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <system-out/>
  <testcase name="P10_OverPayment" time="3.299" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <system-out/>
  <testcase name="C11_Sundry" time="3.316" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <system-out/>
  <testcase name="C11_Writeoff" time="3.750" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <system-out/>
  <testcase name="C11_PerfectMatch" time="10.954" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="C11_BankFee" time="2.384" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <system-out/>
  <testcase name="C11_OverPayment" time="3.055" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="C11_Deduction" time="2.336" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <system-out/>
  <testcase name="C11_Discount" time="3.873" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Discount(InboundTesting.java:312)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- C11_Discount -->
  <system-out/>
  <testcase name="C11_Deduction" time="3.336" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <system-out/>
  <testcase name="P10_PerfectMatch" time="1.767" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <system-out/>
  <testcase name="P10_BankFee" time="3.521" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="P10_Sundry" time="4.346" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="C11_Sundry" time="1.755" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <system-out/>
  <testcase name="C11_OnAccount" time="10.047" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="P10_PerfectMatch" time="1.768" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <system-out/>
  <testcase name="C11_Writeoff" time="3.347" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <system-out/>
  <testcase name="C11_Discount" time="2.350" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <system-out/>
  <testcase name="C11_BankFee" time="2.900" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <system-out/>
  <testcase name="P10_OnAccount" time="1.866" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_OnAccount(InboundTesting.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- P10_OnAccount -->
  <system-out/>
  <testcase name="C11_Writeoff" time="4.470" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Writeoff(InboundTesting.java:349)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- C11_Writeoff -->
  <system-out/>
  <testcase name="P10_ShortPayment" time="0.004" classname="Inbound_Testing.InboundTesting">
    <error type="java.lang.IllegalArgumentException" message="body cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: body cannot be null
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:679)
at com.simple.restassured.RestCalls.PostRequest(RestCalls.java:44)
at Inbound_Testing.InboundTesting.P10_ShortPayment(InboundTesting.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- P10_ShortPayment -->
  <system-out/>
  <testcase name="C11_Writeoff" time="2.307" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <system-out/>
  <testcase name="P10_PerfectMatch" time="2.337" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_PerfectMatch(InboundTesting.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- P10_PerfectMatch -->
  <system-out/>
  <testcase name="C11_Discount" time="3.360" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <system-out/>
  <testcase name="P10_OnAccount" time="2.276" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <system-out/>
  <testcase name="C11_ShortPayment" time="3.784" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="P10_PerfectMatch" time="2.921" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <system-out/>
  <testcase name="C11_Deduction" time="3.849" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <system-out/>
  <testcase name="P10_OverPayment" time="2.282" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <system-out/>
  <testcase name="P10_Deduction" time="3.900" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
  <testcase name="P10_Discount" time="4.223" classname="Inbound_Testing.InboundTesting"/>
  <system-out/>
</testsuite> <!-- Inbound_Testing.InboundTesting -->
