<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="perfectMatch" tests="45" failures="9" timestamp="2021-04-29T14:09:30 IST" time="145.216" errors="0">
  <testcase name="C11_BankFee" time="8.408" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="2.9" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="2.384" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_BankFee" time="3.144" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_BankFee(InboundTesting.java:276)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- C11_BankFee -->
  <testcase name="C11_Deduction" time="3.849" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="2.336" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="3.336" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Deduction" time="2.369" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Deduction(InboundTesting.java:294)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- C11_Deduction -->
  <testcase name="C11_Discount" time="2.35" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="2.986" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="3.36" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_Discount" time="3.873" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Discount(InboundTesting.java:312)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- C11_Discount -->
  <testcase name="C11_OnAccount" time="10.047" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="C11_OverPayment" time="3.055" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="C11_PerfectMatch" time="10.954" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="C11_ShortPayment" time="3.784" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="C11_Sundry" time="1.755" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <testcase name="C11_Sundry" time="3.316" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <testcase name="C11_Sundry" time="2.811" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Sundry -->
  <testcase name="C11_Sundry" time="4.082" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Sundry(InboundTesting.java:330)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- C11_Sundry -->
  <testcase name="C11_Writeoff" time="3.347" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="2.307" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="3.75" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="C11_Writeoff" time="4.47" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.C11_Writeoff(InboundTesting.java:349)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- C11_Writeoff -->
  <testcase name="P10_BankFee" time="3.521" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="P10_Deduction" time="3.9" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="P10_Discount" time="4.223" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="P10_OnAccount" time="2.834" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="2.246" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="2.276" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OnAccount" time="1.866" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_OnAccount(InboundTesting.java:130)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- P10_OnAccount -->
  <testcase name="P10_OverPayment" time="4.108" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="3.299" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="2.282" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_OverPayment" time="2.812" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_OverPayment(InboundTesting.java:148)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- P10_OverPayment -->
  <testcase name="P10_PerfectMatch" time="2.921" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="1.767" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="1.768" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_PerfectMatch" time="2.337" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.AssertionError" message="expected [200] but found [502]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [502]
at com.simple.restassured.Assertions.VerifyStatusCode(Assertions.java:31)
at Inbound_Testing.InboundTesting.P10_PerfectMatch(InboundTesting.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- P10_PerfectMatch -->
  <testcase name="P10_ShortPayment" time="1.141" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.006" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.005" classname="Inbound_Testing.InboundTesting">
    <skipped/>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_ShortPayment" time="0.004" classname="Inbound_Testing.InboundTesting">
    <failure type="java.lang.IllegalArgumentException" message="body cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: body cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:679)
at com.simple.restassured.RestCalls.PostRequest(RestCalls.java:44)
at Inbound_Testing.InboundTesting.P10_ShortPayment(InboundTesting.java:179)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- P10_ShortPayment -->
  <testcase name="P10_Sundry" time="4.346" classname="Inbound_Testing.InboundTesting"/>
  <testcase name="P10_WriteOff" time="2.518" classname="Inbound_Testing.InboundTesting"/>
</testsuite> <!-- perfectMatch -->
